M48
; DRILL file {KiCad (6.0.1)} date Thu Jul 28 19:11:42 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-28T19:11:42-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.5602Y-3.543
X3.5602Y-3.843
X3.5965Y-3.2855
X3.5965Y-4.5847
T0
M30
